name: Build test
on:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: apt install -y bc \
                      binutils-dev \
                      bison \
                      build-essential \
                      ca-certificates \
                      ccache \
                      clang \
                      cmake \
                      curl \
                      file \
                      flex \
                      git \
                      libelf-dev \
                      libssl-dev \
                      lld \
                      make \
                      ninja-build \
                      python3-dev \
                      texinfo \
                      u-boot-tools \
                      xz-utils \
                      zlib1g-dev
    - name: Build llvm
      run: bash build-tc.sh
